### ISSUE TITLE
Ok button stops working after receive with custom pinout

### ISSUE THREAD

**Issue by StevenCollins** [kbembedded/flipper-gb-printer#3]
Setting the pinout to:
SI: PB3
SO: PB2
CLK: PC3

Then selecting "Receive!" causes the Ok button to stop working until a reboot.

It seems to be the same issue as seen here: https://github.com/flipperdevices/flipperzero-firmware/issues/2538

The "Original" pinout uses the same pins (in a different configuration) but doesn't cause the issue, which, after reading that bug report, surprised me. I tried looking through the code to see if I could resolve it on my own, but unfortunately my C isn't that great.

**Comment by kbembedded** [comment]
Can you confirm if you can reproduce this on the latest of what is in git at the moment? Its been a little bit since I tested with the older/MALVEKE pinout, but, it should have been resolved.

**Comment by StevenCollins** [comment]
I built and ran the code in the main branch using uFBT. The issue persists with the pinout settings mentioned in the original post. It works without issue using either the "Original" or "MLVK2.5" pinouts.

**Comment by kbembedded** [comment]
Ah, okay, that was my mistake I had not seen any other custom pinouts used and just incorrectly assumed you were having issues with the MALVEKE style pinouts.

It should be an easy fix since it looks like PC3 also uses the EXTI3 interrupt and most of the exti_workaround code (https://github.com/kbembedded/flipper-gblink/blob/main/gblink/exti_workaround.c) should work.

If you're feeling adventurous, you can try applying the following patch to the `lib/flipper-gblink` folder.

```
diff --git a/gblink/gblink.c b/gblink/gblink.c
index b1792b7d8912..67040ecc6e06 100644
--- a/gblink/gblink.c
+++ b/gblink/gblink.c
@@ -380,7 +380,7 @@ void gblink_start(void *handle)
 	furi_hal_gpio_init(gblink->serin, GpioModeInput, GpioPullUp, GpioSpeedVeryHigh);
 
 	/* Set up interrupt on clock pin */
-	if (gblink->clk == &gpio_ext_pb3) {
+	if (gblink->clk == &gpio_ext_pb3 || gblink->clk == &gpio_ext_pc3) {
 		/* The clock pin is on a pin that is not safe to set an interrupt
 		 * on, so we do a gross workaround to get an interrupt enabled
 		 * on that pin in a way that can be undone safely later with
```

Otherwise, ill try and do some testing on it in the next few days.

It is on my task list to implement the EXTI workaround on any arbitrary pin for the `flipper-gblink` library (multiple GPIO pins share interrupts used by the fact buttons and therefore cannot easily have interrupts enabled on those GPIO pins), but its fairly low priority at this moment.

**Comment by StevenCollins** [comment]
I could have sworn that I searched flipper-gblink for "furi_hal_gpio_init" to find where the GPIO was being initialized so I could see if you had implemented a workaround. It's right there and perfectly commented, I don't know how I missed it.

Your extra OR statement also needed to be added to line 405 where the workaround undo happens, but once it was there it worked perfectly. Thank you!

And thank you for creating this. It's a great way to save Gameboy Camera photos on the go with only the hardware I have lying around. Also, if you were wondering, the pinout I'm using is a completely arbitrary one from a cable I built to interface with an Arduino. It probably would have been easier for me to rebuild the cable with your pinout than to fix your app, but it was also an opportunity for me to learn.

I'll create a PR in flipper-gblink for the change, but since you did all the hard work if you cancel it and implement it yourself I won't be offended.

**Comment by kbembedded** [comment]
> I could have sworn that I searched flipper-gblink for "furi_hal_gpio_init" to find where the GPIO was being initialized so I could see if you had implemented a workaround. It's right there and perfectly commented, I don't know how I missed it.

Yeah, I tried to document the hell out of the workaround because I just knew that months after I originally wrote it and completely forget everything it would be upset at past me.
 
> Your extra OR statement also needed to be added to line 405 where the workaround undo happens, but once it was there it worked perfectly. Thank you!

Hey, good catch, forgot the undo process also had the same check!

> And thank you for creating this. It's a great way to save Gameboy Camera photos on the go with only the hardware I have lying around. Also, if you were wondering, the pinout I'm using is a completely arbitrary one from a cable I built to interface with an Arduino. It probably would have been easier for me to rebuild the cable with your pinout than to fix your app, but it was also an opportunity for me to learn.

Awesome! I'm glad to know people use the app. Helps keep me motivated to keep working on it. And yeah, being able to save photos is nice. If you use the `Photo!` ROM, I'm eventually aiming to be able to use the high-speed transfer modes to quickly dump a whole photo roll.

 
> I'll create a PR in flipper-gblink for the change, but since you did all the hard work if you cancel it and implement it yourself I won't be offended.

Testing the code, making the commit. opening the PR is like 90% of the work. I just happened to have an idea of the right code to change. Cheers, thanks for the contribution!
